[formatter.rust]
command = "rustfmt"
options = ["--edition", "2024"]
include = ["*.rs"]

[formatter.shell]
command = "shfmt"
options = ["-i", "2", "-s", "-w"]
include = ["*.sh"]

[formatter.oxfmt]
command = "oxfmt"
options = ["--write"]
include = [
  "*.css",
  "*.json",
  "*.yaml",
  "*.yml",
  "*.md",
]

[formatter.djlint]
command = "djlint"
options = ["--reformat", "--quiet"]
include = ["*.html"]
